theme: jekyll-theme-minimal

title: Whiteout Capital
description: Private investor publishing independent research focused on microcaps.
url: "https://whiteoutcapital.com"
author:
  name: Whiteout Capital (Zack)
  email: whiteoutcapital@gmail.com
show_downloads: false
logo: /assets/whiteout-profile-small.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
